server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /privacy {
        try_files /privacy.html =404;
    }

    location = /hayat.apk {
        types { application/vnd.android.package-archive apk; }
        add_header Content-Disposition 'attachment; filename="Hayat.apk"';
    }
}
